version: '3'

services:

  spree:
    image: spreecommerce/spree:3.6.4
    ports:
      - "3000:3000"
    networks: 
      - ep1network

  web:
    build: .
    command: python ep1.py
    ports:
      - "5000:5000"
    volumes:
      - .:/todo
    links:
      - mongo
      - spree
      - mongo-express
    networks: 
      - ep1network

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: carlos
      ME_CONFIG_BASICAUTH_PASSWORD: senac2019
      ME_CONFIG_MONGODB_PORT: 27017
      #ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #ME_CONFIG_MONGODB_ADMINPASSWORD: ep1pass
    links:
      - mongo
    networks: 
      - ep1network
  
  mongo:
    image: mongo:4.2
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: ep1pass
    ports:
      - "27017:27017"
    volumes:
      - .:/todo/data/mongodb
    networks:
     - ep1network
    
networks: 
  ep1network:
    driver: bridge